listeCollegate: main.o funzioniListeCollegateEsame.o
	gcc -g -o listeCollegate main.o funzioniListeCollegateEsame.o

main.o: main.c funzioniListeCollegateEsame.h
	gcc -g -c main.c

funzioniListeCollegateEsame.o: funzioniListeCollegateEsame.c
	gcc -g -c funzioniListeCollegateEsame.c