listeCollegate: main.o listeCollegateX.h
	gcc -g -o listeCollegateX main.o listeCollegateX.o

main.o: main.c listeCollegateX.h
	gcc -g -c main.o listeCollegate.o

listeCollegateX.o: listeCollegateX.c
	gcc -g -c listeCollegate.c