scritturaNomi: main.o scritturaNomi.o
	gcc -g -o scritturaNomi main.o scritturaNomi.o

main.o: main.c scritturaNomi.h
	gcc -g -c main.c

scritturaNomi.o: scritturaNomi.c scritturaNomi.h
	gcc -g -c scritturaNomi.c