listeSequenzialiNuove: main.o listeSequenzialiNuove.o
	gcc -g -o listeSequenzialiNuove main.o listeSequenzialiNuove.o

main.o: main.c listeSequenzialiNuove.h
	gcc -g -c main.c

listeSequenzialiNuove.o: listeSequenzialiNuove.c listeSequenzialiNuove.h
	gcc -g -c listeSequenzialiNuove.c