giornata: main.o listaGiornate.o
	gcc -g -o giornata main.o listaGiornate.o

main.o: main.c listaGiornate.h
	gcc -g -c main.c

listaGiornate.o: listaGiornate.c listaGiornate.h
	gcc -g -c listaGiornate.c