tengenListeSequenziali: main.o prot_liste_sequenziali.o
	gcc -g -o tengenListeSequenziali main.o prot_liste_sequenziali.o

 main.o: main.c prot_liste_sequenziali.h
	gcc -g -c main.c

prot_liste_sequenziali.o: prot_liste_sequenziali.c
	gcc -g -c prot_liste_sequenziali.c