provaListeCollegate: main.o listeCollegatePrototipi.o
	gcc -g -o provaListeCollegate main.o listeCollegatePrototipi.o

main.o: main.c listeCollegatePrototipi.h
	gcc -g -c main.c

listeCollegatePrototipi.o: listeCollegatePrototipi.c
	gcc -g -c listeCollegatePrototipi.c