tutteFunzioniListeCollegate: main.o tutteFunzioniListeCollegate.o
	gcc -g -o tutteFunzioniListeCollegate main.o tutteFunzioniListeCollegate.o

main.o: main.c tutteFunzioniListeCollegate.h
	gcc -g -c main.c 

tutteFunzioniListeCollegate.o: tutteFunzioniListeCollegate.c
	gcc -g -c tutteFunzioniListeCollegate.c