grandeArray: main.o funzioneGrandeArray.o
	gcc -g -o grandeArray main.o funzioneGrandeArray.o

main.o: main.c funzioneGrandeArray.h
	gcc -g -c main.c

funzioneGrandeArray.o: funzioneGrandeArray.c
	gcc -g -c funzioneGrandeArray.c