---
- hosts: web
  vars_files:
    - vars.yml
  
  tasks:
    - name: "aggiornamento repository"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: upgrade dei pacchetti
      apt:
        upgrade: yes
    
    - name: "installazione pacchetti rsyslog e logrotate"
      apt:
        name: ['rsylog', 'logrotate']
    
    - name: "copia sryslog"
      template:
        src: rsyslog.conf
        dest: /etc/rsyslog/rsyslog.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: "copia logrotate.conf"
      template:
        src: logrotate.conf
        dest: /ect/logrotate/logrotate.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "enable e start di rsyslog"
      ansible.builtin.systemd:
        name: rsyslog
        state: restarted
        enabled: yes

    - name: "enable e start di logrotate"
      systemd:
        name: logrotate
        state: restarted
        enabled: yes