funzioneListToArray: main.o listToArray.o
	gcc -g -o funzioneListToArray main.o listToArray.o

main.o: main.c listToArray.h
	gcc -g -c main.c

listToArray.o: listToArray.c listToArray.h
	gcc -g -c listToArray.c