##################################################
# LEMP Linux Nginx MySql Php
##################################################
---
- hosts: web
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    - name: Stop apache2 if running
      systemd:
        name: 'apache2'
        state: stopped

    - name: Also disable apache2
      systemd:
        name: 'apache2'
        enabled: no

    - name: Install LEMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx', 'mariadb-server', 'python3-pymysql', 'php-fpm', 'php-mysql' ]
    
  # Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_host }}"

    - name: Enables the new site via symlink
      file:
        src: "/etc/nginx/sites-available/{{ http_host }}"
        dest: "/etc/nginx/sites-enabled/{{ http_host }}"
        state: link

    - name: Delete old site directory if present
      file:
        path: /var/www/{{ http_host}}/
        state: absent
    
    - name: Create site directory
      file:
        path: /var/www/{{ http_host }}/
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    # check note at https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#examples

    # Copy the mysql credential file to /root/.my.cnf
    - name: Create mysql credential file
      template:
        src: "files/mysql_conf_file.j2"
        dest: "/root/.my.cnf"

    # MySQL set root password
    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    # Sets Up a simple PHP website download from Github in the files dir
    - name: Sets Up PHP Info Page
      copy:
        src: "files/simple-php-website/"
        dest: "/var/www/{{ http_host }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Restart Nginx 
      ansible.builtin.systemd:
        name: nginx 
        state: restarted
        enabled: yes
