esercizioListeSequenziali: main.o listeSequenzialiPrototipi.o
	gcc -g -o esercizioListeSequenziali main.o listeSequenzialiPrototipi.o

main.o: main.c listeSequenzialiPrototipi.h
	gcc -g -c main.c

listeSequenzialiPrototipi.o: listeSequenzialiPrototipi.c
	gcc -g -c listeSequenzialiPrototipi.c