svolazziDiClassicismo: main.o svolazziDiClassicismo.o
	gcc -g -o svolazziDiClassicismo main.o svolazziDiClassicismo.o

main.o: main.c svolazziDiClassicismo.h
	gcc -g -c main.c

svolazziDiClassicismo.o: svolazziDiClassicismo.c 
	gcc -g -c svolazziDiClassicismo.c