---
- hosts: lighttpd-webserver
  vars_files:
    - vars.yml
  tasks:
    - name: "Aggiornamento e upgrade"
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: "Installazione lighttpd e memcached"
      apt:
        name: ['lighttpd', 'memcached']
        state: latest
    
    - name: "Copia la directory blogging"
      copy:
        src: files/blogging
        dest: /var/www/html/(( website_domain ))
        owner: "{{ lighttpd_user }}"
        group: "{{ lighttpd_user}}"
        mode: 0755

    - name: "Copia file di configurazione"
      template:
        src: lighttpd.conf.j2
        dest: /etc/lighttpd/lighttpd.conf
        owner: "{{ lighttpd_user }}"
        group: "{{ lighttpd_user }}"
      
    - name: "Riavvio il servizio di lighttpd"
      systemd:
        name: lighttpd
        state: restarted