pariDispari: main.o funzione_pari_dispari.o
	gcc -g -o pariDispari main.o funzione_pari_dispari.o

main.o: main.c funzione_pari_dispari.h
	gcc -g -c main.c

funzione_pari_dispari.o: funzione_pari_dispari.c
	gcc -g -c funzione_pari_dispari.c